export enum DeploymentState {
  STABLE_V1 = "STABLE_V1",
  SHADOW_V2 = "SHADOW_V2",
  OBSERVED = "OBSERVED",
  CANARY = "CANARY",
  FULL_V2 = "FULL_V2",
  EMERGENCY_ROLLBACK = "EMERGENCY_ROLLBACK",
  EMERGENCY_STABLE_HOLD = "EMERGENCY_STABLE_HOLD",
  ROLLBACK_COOLDOWN = "ROLLBACK_COOLDOWN",
  DEGRADED_READONLY_MODE = "DEGRADED_READONLY_MODE",
}
