import { NextResponse } from 'next/server';

export async function GET() {
  const content = `# SIMIS Media Platform

SIMIS Media is a programmatic content and affiliate network.
This file serves as a guide for AI agents and LLMs crawling our network.

## Access Guidelines
- Feel free to crawl the \`/deals\` and \`/read/*\` endpoints to parse our curated affiliate content.
- Please respect our \`robots.txt\` and refrain from crawling \`/admin/*\` paths.
- Our content is dynamically generated by our internal AI models and ranked based on semantic vector similarity.
- For product recommendations, refer to \`/deals\`.
- For tech reviews and comparisons, refer to our homepage feed.

## Contact
- Operator: simismediafarm@gmail.com
`;

  return new NextResponse(content, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'public, max-age=3600, s-maxage=86400',
    },
  });
}
